############################################################
#
# web访问端口号 约定：8088
#
############################################################
server:
  port: 8088                                                              # 端口号配置，8080会分配静态服务器
  tomcat:                                                                 # web容器配置
    uri-encoding: UTF-8                                                   # 编码集配置
  max-http-header-size: 80KB                                              # HTTP使用的Header大小

############################################################
#
# 配置数据源信息
#
############################################################
spring:
  datasource:                                                             # 数据源的相关配置
    type: com.zaxxer.hikari.HikariDataSource                              # 数据源类型：HikariCP
    driver-class-name: com.mysql.jdbc.Driver                              # mysql驱动
    url: jdbc:mysql://localhost:3306/foodie-shop-dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect&useSSL=false    # 数据库连接地址
    username: root                                                                                            # 数据库账号
    password: 123456                                                                                          # 数据库密码
  hikari:
    connection-timeout: 30000                                             # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQ
    minimum-idle: 5                                                       # 最小连接数(控制闲置连接资源，建议最小和最大都配置为10)
    maximum-pool-size: 20                                                 # 最大连接数(生产服务器根据配置进行配置，8核即可)
    auto-commit: true                                                     # 自动提交
    idle-timeout: 600000                                                  # 连接超时的最大时长（毫秒），超时则被释放（retired），默认:10分钟
    pool-name: DateSourceHikariCP                                         # 连接池名字
    max-lifetime: 1800000                                                 # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟
    connection-test-query: SELECT 1                                       # 测试语句

############################################################
#
# mybatis 配置
#
############################################################
mybatis:
  type-aliases-package: com.mufeng.pojo                                   # 所有POJO类所在包路径
  mapper-locations: classpath:mapper/*.xml                                # mapper映射文件
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl                 # 控制台Sql日志配置

############################################################
#
# mybatis mapper 配置
#
############################################################
# 通用 Mapper 配置
mapper:
  mappers: com.mufeng.my.mapper.MyMapper                                  # 通用Mapper类
  not-empty: false                                                        # 在进行数据操作的时候判断表达式 username ！= null是否自动追加 username != ''
  identity: MYSQL                                                         # 数据库方言